train_data: C:/Users/user/Desktop/megacorpus/reports_u/gt_reports_u_training_full_path.txt
valid_data: "C:/Users/user/Desktop/megacorpus/reports_u/gt_reports_u_test_full_path.txt"
save_path: "C:/Users/user/Desktop/results111/config_8"
manualSeed: 1111
workers: 8
batch_size: 64
num_iter: 300000
valInterval: 5000
no_improve: 10
saved_model: ''
FT: false
adam: false
lr: 1.0
beta1: 0.9
rho: 0.95
eps: 1e-8
grad_clip: 5
baiduCTC: false
select_data: MJ-ST
batch_ratio: '1'
total_data_usage_ratio: 1.0
batch_max_length: 24
imgH: 100
imgW: 330
rgb: false
character: "0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyzАБВГДЕЁЖЗИЙКЛМНОПРСТУФХЦЧШЩЪЫЬЭЮЯабвгдеёжзийклмнопрстуфхцчшщъыьэюя!\"#$%&'()*+,-./:;<=>?@[\\]№_`{|}~ €₽"
sensitive: true
PAD: false
data_filtering_off: false
Transformation: None
FeatureExtraction: ResNet
SequenceModeling: BiLSTM
Prediction: Attn
num_fiducial: 20
input_channel: 1
output_channel: 128
hidden_size: 128