train_data: C:/Users/user/Desktop/megacorpus/reports/gt_reports_training.txt
valid_data: "C:/Users/user/Desktop/megacorpus/reports/gt_reports_test.txt"
exp_name: C:/Users/user/Desktop/megacorpus/exp1
manualSeed: 1111
workers: 8
batch_size: 256
num_iter: 200000
valInterval: 10000
saved_model: ''
FT: false
adam: false
lr: 1.0
beta1: 0.9
rho: 0.95
eps: 1e-8
grad_clip: 5
baiduCTC: false
select_data: MJ-ST
batch_ratio: '1'
total_data_usage_ratio: 1.0
batch_max_length: 24
imgH: 70
imgW: 150
rgb: false
character: "0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyzАБВГДЕЁЖЗИЙКЛМНОПРСТУФХЦЧШЩЪЫЬЭЮЯабвгдеёжзийклмнопрстуфхцчшщъыьэюя!\"#$%&'()*+,-./:;<=>?@[\\]№_`{|}~ €₽"
sensitive: true
PAD: false
data_filtering_off: false
Transformation: None
FeatureExtraction: VGG
SequenceModeling: ResNet
Prediction: CTC
num_fiducial: 20
input_channel: 1
output_channel: 128
hidden_size: 128