Transformation: TPS
FeatureExtraction: ResNet
SequenceModeling: None
Prediction: Attn

imgH: 64
imgW: 256

input_channel: 1
output_channel: 256
hidden_size: 256

batch_max_length: 25
num_fiducial: 20

rgb: false
character: " !%'()*+,-./0123456789:;<=>[]^_v{|}~§«»АБВГДЕЖЗИЙКЛМНОПРСТУФХЦЧШЩЪЫЬЭЮЯабвгдежзийклмнопрстуфхцчшщъыьэюяёіѣѳѵ№"